influxdb:
  #build: .
  image: influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
  environment:
    ADMIN_USER: admin
    INFLUXDB_INIT_PWD: admin
    PRE_CREATE_DB: 1wire
  volumes:
      - ./data/influxdb:/var/lib/influxdb

grafana:
  #image: grafana/grafana
  image: monitoringartist/grafana-xxl
  ports:
    - "3000:3000"
  volumes:
      - ./data/grafana:/var/lib/grafana
  links:
    - influxdb
